name: animated
description: A new Flutter application.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_webview_plugin: ^0.3.11
  # webview_flutter: ^0.3.22+1
  dio: ^3.0.9
  progress_dialog: ^1.2.4
  material_design_icons_flutter: ^4.0.5555
  dotted_border: ^1.0.6
  file_picker: ^1.13.2
  intl: ^0.16.1
  pull_to_refresh: ^1.6.0
  shared_preferences: ^0.5.8
  http: ^0.12.2
  flutter_downloader: ^1.5.0
  permission_handler: ^5.0.1+1
  provider: ^4.3.1
  path_provider: ^1.6.11
  connectivity: ^0.4.9
  fluttertoast: ^7.1.1
  # percent_indicator: ^2.1.5
  flutter_screenutil: ^3.2.0
  flutter_launcher_icons: ^0.8.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/slides/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fileTypes/
    - assets/icons/
    - assets/slides/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilory-Medium
      fonts:       
        - asset: assets/fonts/Gilroy-Font/Gilroy-Medium.ttf
    - family: Gilory
      fonts:     
        - asset: assets/fonts/Gilroy-Font/Gilroy-Bold.ttf
    - family: Gilory-Reg
      fonts:
        - asset: assets/fonts/Gilroy-Font/Gilroy-Regular.ttf
        
        #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
