name: school
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7
  camera: ^0.5.7+4
  path_provider: ^1.6.7
  video_player: ^0.10.8+1
  http: ^0.12.1
  fluttertoast: ^4.0.1
  connectivity: ^0.4.8
  intl: ^0.16.1
  flutter_multiselect: ^0.4.0
  image_picker: ^0.6.6+1
  flutter_downloader: ^1.4.4
  file_picker: ^1.9.0+1
  mime: ^0.9.6+3
  toast: ^0.1.5
  flutter_webview_plugin: ^0.3.11
  dio: ^3.0.9




  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
